### ISSUE TITLE
[Feature request]: 催更最新的6.43

### ISSUE THREAD

**Issue by hzc54188** [ShiinaRinne/v2rayN#2]
### 相关问题

最新的6.43开始支持wireguard

### 描述你希望的解决方案

更新一下版本

### 我确认已查询历史issues

- [X] 是

**Comment by ShiinaRinne** [comment]
https://github.com/ShiinaRinne/v2rayN/releases/tag/6.53

更了. 
不好意思, 之前都没看到有这个 issue 的提醒, 还是今天点进来才看见有个新的XD
