### ISSUE TITLE
提问关于此分支的pac模式问题

### ISSUE THREAD

**Issue by Aftertea123** [ShiinaRinne/v2rayN#4]
先说一声不好意思，可能是因为我不太会用的关系，切换成这个分支的v2ray之后pac模式就无法正常代理了，想问一下这比起原本的pac模式需要额外调整什么东西吗,我的pac好像无论什么都不会代理了

**Comment by Aftertea123** [comment]
我又研究了一会儿 发现是本地socks监听端口的问题 只要调成别的端口就会无法代理 默认的10808就没什么问题

**Comment by ShiinaRinne** [comment]
看看 `设置->v2rayN设置->自定义pac代理端口`
我出于某些需求添加了这个功能，用来覆盖原本pac文件中的端口。
如果这个你没改过，而又更改了 xray 默认监听的端口时，请求将会转发到未使用的端口上。

你也可以在 windows 的代理设置中查看 pac 的地址，并粘贴到浏览器，下载生成之后的 pac 文件，观察这个文件中的端口指向

**Comment by Aftertea123** [comment]
哦哦 感谢回复 问题已经解决了 非常感谢
